openapi: 3.0.3
info:
  title: Play-J Payment Service
  description: Microservice for payment operations
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for payment
paths:
  /api/v1/payment-service/payments:
    get:
      tags:
      - payment
      summary: getAccountPayments payment
      operationId: payment#getAccountPayments
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentListResponse'
              example:
                resources:
                - amount: 0.6914599
                  createdAt: Eos iusto saepe aut exercitationem eaque libero.
                  id: 4888721511633999565
                  paymentNumber: Aut id.
                - amount: 0.6914599
                  createdAt: Eos iusto saepe aut exercitationem eaque libero.
                  id: 4888721511633999565
                  paymentNumber: Aut id.
                - amount: 0.6914599
                  createdAt: Eos iusto saepe aut exercitationem eaque libero.
                  id: 4888721511633999565
                  paymentNumber: Aut id.
                total: 4398530068892633877
    post:
      tags:
      - payment
      summary: createAccountPayment payment
      operationId: payment#createAccountPayment
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
              example:
                message: Impedit rerum cumque tempora odit debitis autem.
                paymentNumber: Dolores nostrum harum eveniet.
components:
  schemas:
    PaymentListResponse:
      type: object
      properties:
        resources:
          type: array
          items:
            $ref: '#/components/schemas/PaymentResponse'
          description: Resournces
          example:
          - amount: 0.6914599
            createdAt: Eos iusto saepe aut exercitationem eaque libero.
            id: 4888721511633999565
            paymentNumber: Aut id.
          - amount: 0.6914599
            createdAt: Eos iusto saepe aut exercitationem eaque libero.
            id: 4888721511633999565
            paymentNumber: Aut id.
          - amount: 0.6914599
            createdAt: Eos iusto saepe aut exercitationem eaque libero.
            id: 4888721511633999565
            paymentNumber: Aut id.
          - amount: 0.6914599
            createdAt: Eos iusto saepe aut exercitationem eaque libero.
            id: 4888721511633999565
            paymentNumber: Aut id.
        total:
          type: integer
          description: Total number of resources
          example: 9820895026952485780
      example:
        resources:
        - amount: 0.6914599
          createdAt: Eos iusto saepe aut exercitationem eaque libero.
          id: 4888721511633999565
          paymentNumber: Aut id.
        - amount: 0.6914599
          createdAt: Eos iusto saepe aut exercitationem eaque libero.
          id: 4888721511633999565
          paymentNumber: Aut id.
        - amount: 0.6914599
          createdAt: Eos iusto saepe aut exercitationem eaque libero.
          id: 4888721511633999565
          paymentNumber: Aut id.
        total: 6109190808011266092
      required:
      - total
      - resources
    PaymentResponse:
      type: object
      properties:
        amount:
          type: number
          description: Payment amount
          example: 0.96438646
          format: float
        createdAt:
          type: string
          description: Time of creation
          example: Non eum omnis est.
        id:
          type: integer
          description: Id
          example: 7574210935021280401
        paymentNumber:
          type: string
          description: Payment Number
          example: Blanditiis deleniti eveniet voluptate eligendi esse.
      example:
        amount: 0.088960916
        createdAt: Nostrum mollitia error laudantium voluptatem laudantium.
        id: 4242734298011617092
        paymentNumber: Ex quisquam.
      required:
      - id
      - createdAt
      - paymentNumber
      - amount
    TransactionResponse:
      type: object
      properties:
        message:
          type: string
          description: Operation status
          example: Provident voluptatem.
        paymentNumber:
          type: string
          description: Payment Unique Number
          example: Autem eum laboriosam accusantium.
      example:
        message: Et ipsa.
        paymentNumber: Sunt dolores tempore illo vel voluptatum.
      required:
      - paymentNumber
      - message
tags:
- name: payment
  description: Payment operations
