swagger: "2.0"
info:
  title: Play-J Payment Service
  description: Microservice for payment operations
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/payment-service/payments:
    get:
      tags:
      - payment
      summary: getAccountPayments payment
      operationId: payment#getAccountPayments
      parameters:
      - name: limit
        in: query
        description: Resource array size
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PaymentGetAccountPaymentsResponseBody'
            required:
            - total
            - resources
      schemes:
      - http
    post:
      tags:
      - payment
      summary: createAccountPayment payment
      operationId: payment#createAccountPayment
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PaymentCreateAccountPaymentResponseBody'
            required:
            - paymentNumber
            - message
      schemes:
      - http
  /api/v1/payment-service/subscriptions:
    get:
      tags:
      - subscription
      summary: getAccountSubscriptionStatus subscription
      operationId: subscription#getAccountSubscriptionStatus
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SubscriptionGetAccountSubscriptionStatusResponseBody'
            required:
            - hasPaid
            - validUntil
            - type
      schemes:
      - http
definitions:
  PaymentCreateAccountPaymentResponseBody:
    title: PaymentCreateAccountPaymentResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation status
        example: Nostrum mollitia error laudantium voluptatem laudantium.
      paymentNumber:
        type: string
        description: Payment Unique Number
        example: Eligendi esse iste quia.
    example:
      message: Non modi sed debitis autem.
      paymentNumber: Ex quisquam.
    required:
    - paymentNumber
    - message
  PaymentGetAccountPaymentsResponseBody:
    title: PaymentGetAccountPaymentsResponseBody
    type: object
    properties:
      resources:
        type: array
        items:
          $ref: '#/definitions/PaymentResponseResponseBody'
        description: Resournces
        example:
        - amount: 0.045109253
          createdAt: Repudiandae dolores nostrum harum.
          id: 5614265788585208775
          paymentNumber: Dolor impedit rerum.
        - amount: 0.045109253
          createdAt: Repudiandae dolores nostrum harum.
          id: 5614265788585208775
          paymentNumber: Dolor impedit rerum.
        - amount: 0.045109253
          createdAt: Repudiandae dolores nostrum harum.
          id: 5614265788585208775
          paymentNumber: Dolor impedit rerum.
      total:
        type: integer
        description: Total number of resources
        example: 12576430019621352510
        format: int64
    example:
      resources:
      - amount: 0.045109253
        createdAt: Repudiandae dolores nostrum harum.
        id: 5614265788585208775
        paymentNumber: Dolor impedit rerum.
      - amount: 0.045109253
        createdAt: Repudiandae dolores nostrum harum.
        id: 5614265788585208775
        paymentNumber: Dolor impedit rerum.
      total: 4396716847613175530
    required:
    - total
    - resources
  PaymentResponseResponseBody:
    title: PaymentResponseResponseBody
    type: object
    properties:
      amount:
        type: number
        description: Payment amount
        example: 0.5583874
        format: float
      createdAt:
        type: string
        description: Time of creation
        example: Rerum animi.
      id:
        type: integer
        description: Id
        example: 9981160763808931699
        format: int64
      paymentNumber:
        type: string
        description: Payment Number
        example: Excepturi sint.
    example:
      amount: 0.5680312
      createdAt: Ut sed vitae.
      id: 6047946286363235355
      paymentNumber: Non eum omnis est.
    required:
    - id
    - createdAt
    - paymentNumber
    - amount
  SubscriptionGetAccountSubscriptionStatusResponseBody:
    title: SubscriptionGetAccountSubscriptionStatusResponseBody
    type: object
    properties:
      hasPaid:
        type: boolean
        description: Is the subscrion paid or not
        example: true
      type:
        type: string
        description: Subscription type
        example: Voluptatem facilis sunt dolores tempore.
      validUntil:
        type: string
        description: Subscription end date
        example: Accusantium commodi.
    example:
      hasPaid: false
      type: Blanditiis ipsam amet.
      validUntil: Voluptatum quia et.
    required:
    - hasPaid
    - validUntil
    - type
