swagger: "2.0"
info:
  title: Play-J Player Service
  description: Microservice for streaming music files over the network
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/player-service/tracks/{trackID}:
    get:
      tags:
      - player
      summary: getTrackByID player
      operationId: player#getTrackByID
      parameters:
      - name: trackID
        in: path
        description: ID of the Track
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlayerGetTrackByIDResponseBody'
      schemes:
      - http
definitions:
  PlayerGetTrackByIDResponseBody:
    title: 'Mediatype identifier: audio/mpeg; view=default'
    type: object
    properties:
      file:
        type: string
        example:
        - 86
        - 111
        - 108
        - 117
        - 112
        - 116
        - 97
        - 115
        - 32
        - 101
        - 116
        - 32
        - 102
        - 117
        - 103
        - 97
        - 32
        - 118
        - 105
        - 116
        - 97
        - 101
        - 32
        - 117
        - 110
        - 100
        - 101
        - 32
        - 113
        - 117
        - 111
        - 46
        format: byte
    description: GetTrackByIDResponseBody result type (default view)
    example:
      file:
      - 86
      - 101
      - 114
      - 111
      - 32
      - 97
      - 112
      - 101
      - 114
      - 105
      - 97
      - 109
      - 32
      - 118
      - 101
      - 110
      - 105
      - 97
      - 109
      - 32
      - 109
      - 97
      - 103
      - 110
      - 97
      - 109
      - 32
      - 113
      - 117
      - 105
      - 32
      - 101
      - 115
      - 116
      - 32
      - 101
      - 110
      - 105
      - 109
      - 46
