openapi: 3.0.3
info:
  title: Play-J Player Service
  description: Microservice for streaming music files over the network
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for player
paths:
  /api/v1/player-service/tracks/{trackID}:
    get:
      tags:
      - player
      summary: getTrackByID player
      operationId: player#getTrackByID
      parameters:
      - name: trackID
        in: path
        description: ID of the Track
        required: true
        schema:
          type: integer
          description: ID of the Track
          example: 15849484324231435404
        example: 4274324650275255288
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MusicFileResponse'
              example:
                file:
                - 72
                - 97
                - 114
                - 117
                - 109
                - 32
                - 117
                - 116
                - 32
                - 105
                - 110
                - 118
                - 101
                - 110
                - 116
                - 111
                - 114
                - 101
                - 32
                - 101
                - 115
                - 115
                - 101
                - 32
                - 105
                - 100
                - 46
components:
  schemas:
    MusicFileResponse:
      type: object
      properties:
        file:
          type: string
          example:
          - 77
          - 105
          - 110
          - 105
          - 109
          - 97
          - 32
          - 99
          - 111
          - 109
          - 109
          - 111
          - 100
          - 105
          - 32
          - 113
          - 117
          - 111
          - 100
          - 32
          - 100
          - 111
          - 108
          - 111
          - 114
          - 101
          - 109
          - 46
          format: binary
      example:
        file:
        - 81
        - 117
        - 111
        - 32
        - 101
        - 116
        - 32
        - 113
        - 117
        - 105
        - 98
        - 117
        - 115
        - 100
        - 97
        - 109
        - 32
        - 118
        - 101
        - 108
        - 105
        - 116
        - 32
        - 115
        - 111
        - 108
        - 117
        - 116
        - 97
        - 32
        - 100
        - 111
        - 108
        - 111
        - 114
        - 101
        - 32
        - 101
        - 116
        - 46
tags:
- name: player
  description: Player operations
