swagger: "2.0"
info:
  title: Play-J Player Service
  description: Microservice for streaming music files over the network
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/player-service/tracks/{trackID}:
    post:
      tags:
      - player
      summary: getTrackByID player
      operationId: player#getTrackByID
      parameters:
      - name: trackID
        in: path
        description: ID of the Track
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlayerGetTrackByIDResponseBody'
            required:
            - track
      schemes:
      - http
definitions:
  PlayerGetTrackByIDResponseBody:
    title: PlayerGetTrackByIDResponseBody
    type: object
    properties:
      track:
        type: array
        items:
          type: string
          example:
          - 65
          - 110
          - 105
          - 109
          - 105
          - 32
          - 113
          - 117
          - 111
          - 32
          - 101
          - 116
          - 32
          - 113
          - 117
          - 105
          - 98
          - 117
          - 115
          - 100
          - 97
          - 109
          - 32
          - 118
          - 101
          - 108
          - 105
          - 116
          - 32
          - 115
          - 111
          - 108
          - 117
          - 116
          - 97
          - 46
          format: byte
        description: Operation completion status
        example:
        - - 77
          - 105
          - 110
          - 105
          - 109
          - 97
          - 32
          - 100
          - 105
          - 99
          - 116
          - 97
          - 46
        - - 69
          - 116
          - 32
          - 115
          - 105
          - 116
          - 32
          - 101
          - 114
          - 114
          - 111
          - 114
          - 46
        - - 86
          - 105
          - 116
          - 97
          - 101
          - 32
          - 101
          - 120
          - 32
          - 113
          - 117
          - 105
          - 32
          - 115
          - 105
          - 116
          - 46
    example:
      track:
      - - 69
        - 117
        - 109
        - 32
        - 118
        - 111
        - 108
        - 117
        - 112
        - 116
        - 97
        - 115
        - 32
        - 114
        - 101
        - 112
        - 114
        - 101
        - 104
        - 101
        - 110
        - 100
        - 101
        - 114
        - 105
        - 116
        - 32
        - 110
        - 117
        - 108
        - 108
        - 97
        - 32
        - 115
        - 117
        - 110
        - 116
        - 46
      - - 82
        - 101
        - 112
        - 101
        - 108
        - 108
        - 101
        - 110
        - 100
        - 117
        - 115
        - 32
        - 110
        - 117
        - 108
        - 108
        - 97
        - 32
        - 109
        - 97
        - 103
        - 110
        - 97
        - 109
        - 32
        - 101
        - 120
        - 99
        - 101
        - 112
        - 116
        - 117
        - 114
        - 105
        - 32
        - 109
        - 97
        - 103
        - 110
        - 105
        - 32
        - 97
        - 115
        - 115
        - 117
        - 109
        - 101
        - 110
        - 100
        - 97
        - 32
        - 113
        - 117
        - 105
        - 46
      - - 67
        - 111
        - 114
        - 114
        - 117
        - 112
        - 116
        - 105
        - 32
        - 99
        - 117
        - 109
        - 32
        - 97
        - 99
        - 99
        - 117
        - 115
        - 97
        - 109
        - 117
        - 115
        - 32
        - 118
        - 101
        - 108
        - 46
      - - 79
        - 112
        - 116
        - 105
        - 111
        - 32
        - 109
        - 111
        - 108
        - 101
        - 115
        - 116
        - 105
        - 97
        - 101
        - 32
        - 114
        - 101
        - 114
        - 117
        - 109
        - 32
        - 101
        - 117
        - 109
        - 32
        - 101
        - 117
        - 109
        - 32
        - 113
        - 117
        - 105
        - 32
        - 118
        - 111
        - 108
        - 117
        - 112
        - 116
        - 97
        - 116
        - 101
        - 109
        - 46
    required:
    - track
