openapi: 3.0.3
info:
  title: Play-J Player Service
  description: Microservice for streaming music files over the network
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for player
paths:
  /api/v1/player-service/tracks/{trackID}:
    get:
      tags:
      - player
      summary: getTrackByID player
      operationId: player#getTrackByID
      parameters:
      - name: trackID
        in: path
        description: ID of the Track
        required: true
        schema:
          type: integer
          description: ID of the Track
          example: 3465175292282028801
        example: 8178752941220215374
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamTrackResponse'
              example:
                track:
                - 73
                - 112
                - 115
                - 97
                - 109
                - 32
                - 101
                - 97
                - 113
                - 117
                - 101
                - 46
components:
  schemas:
    StreamTrackResponse:
      type: object
      properties:
        track:
          type: string
          description: Operation completion status
          example:
          - 86
          - 101
          - 114
          - 111
          - 32
          - 97
          - 112
          - 101
          - 114
          - 105
          - 97
          - 109
          - 32
          - 118
          - 101
          - 110
          - 105
          - 97
          - 109
          - 32
          - 109
          - 97
          - 103
          - 110
          - 97
          - 109
          - 32
          - 113
          - 117
          - 105
          - 32
          - 101
          - 115
          - 116
          - 32
          - 101
          - 110
          - 105
          - 109
          - 46
          format: binary
      example:
        track:
        - 77
        - 105
        - 110
        - 105
        - 109
        - 97
        - 32
        - 99
        - 111
        - 109
        - 109
        - 111
        - 100
        - 105
        - 32
        - 113
        - 117
        - 111
        - 100
        - 32
        - 100
        - 111
        - 108
        - 111
        - 114
        - 101
        - 109
        - 46
      required:
      - track
tags:
- name: player
  description: Player operations
