openapi: 3.0.3
info:
  title: Play-J Player Service
  description: Microservice for streaming music files over the network
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for player
paths:
  /api/v1/player-service/tracks/{trackID}:
    post:
      tags:
      - player
      summary: getTrackByID player
      operationId: player#getTrackByID
      parameters:
      - name: trackID
        in: path
        description: ID of the Track
        required: true
        schema:
          type: integer
          description: ID of the Track
          example: 16108483667557787559
        example: 8880182133860377261
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamTrackResponse'
              example:
                track:
                - - 86
                  - 111
                  - 108
                  - 117
                  - 112
                  - 116
                  - 97
                  - 116
                  - 105
                  - 98
                  - 117
                  - 115
                  - 32
                  - 118
                  - 111
                  - 108
                  - 117
                  - 112
                  - 116
                  - 97
                  - 115
                  - 32
                  - 101
                  - 116
                  - 32
                  - 102
                  - 117
                  - 103
                  - 97
                  - 32
                  - 118
                  - 105
                  - 116
                  - 97
                  - 101
                  - 46
                - - 81
                  - 117
                  - 111
                  - 32
                  - 100
                  - 111
                  - 108
                  - 111
                  - 114
                  - 32
                  - 118
                  - 101
                  - 114
                  - 111
                  - 32
                  - 97
                  - 112
                  - 101
                  - 114
                  - 105
                  - 97
                  - 109
                  - 32
                  - 118
                  - 101
                  - 110
                  - 105
                  - 97
                  - 109
                  - 32
                  - 109
                  - 97
                  - 103
                  - 110
                  - 97
                  - 109
                  - 46
                - - 69
                  - 115
                  - 116
                  - 32
                  - 101
                  - 110
                  - 105
                  - 109
                  - 32
                  - 97
                  - 116
                  - 46
                - - 67
                  - 111
                  - 109
                  - 109
                  - 111
                  - 100
                  - 105
                  - 32
                  - 113
                  - 117
                  - 111
                  - 100
                  - 46
components:
  schemas:
    StreamTrackResponse:
      type: object
      properties:
        track:
          type: array
          items:
            type: string
            example:
            - 85
            - 116
            - 32
            - 110
            - 111
            - 98
            - 105
            - 115
            - 32
            - 113
            - 117
            - 111
            - 100
            - 46
            format: binary
          description: Operation completion status
          example:
          - - 82
            - 97
            - 116
            - 105
            - 111
            - 110
            - 101
            - 32
            - 115
            - 117
            - 110
            - 116
            - 32
            - 102
            - 97
            - 99
            - 101
            - 114
            - 101
            - 46
          - - 83
            - 117
            - 110
            - 116
            - 32
            - 102
            - 97
            - 99
            - 101
            - 114
            - 101
            - 32
            - 113
            - 117
            - 97
            - 101
            - 114
            - 97
            - 116
            - 32
            - 118
            - 111
            - 108
            - 117
            - 112
            - 116
            - 97
            - 116
            - 101
            - 109
            - 32
            - 105
            - 100
            - 32
            - 115
            - 97
            - 101
            - 112
            - 101
            - 32
            - 118
            - 111
            - 108
            - 117
            - 112
            - 116
            - 97
            - 115
            - 46
          - - 81
            - 117
            - 97
            - 101
            - 32
            - 99
            - 117
            - 109
            - 46
      example:
        track:
        - - 82
          - 101
          - 112
          - 101
          - 108
          - 108
          - 97
          - 116
          - 32
          - 109
          - 97
          - 120
          - 105
          - 109
          - 101
          - 32
          - 113
          - 117
          - 97
          - 101
          - 32
          - 102
          - 117
          - 103
          - 105
          - 97
          - 116
          - 32
          - 111
          - 112
          - 116
          - 105
          - 111
          - 46
        - - 68
          - 111
          - 108
          - 111
          - 114
          - 101
          - 109
          - 32
          - 100
          - 111
          - 108
          - 111
          - 114
          - 101
          - 32
          - 114
          - 101
          - 112
          - 117
          - 100
          - 105
          - 97
          - 110
          - 100
          - 97
          - 101
          - 32
          - 116
          - 101
          - 109
          - 112
          - 111
          - 114
          - 105
          - 98
          - 117
          - 115
          - 32
          - 110
          - 97
          - 116
          - 117
          - 115
          - 32
          - 105
          - 112
          - 115
          - 97
          - 46
        - - 68
          - 105
          - 99
          - 116
          - 97
          - 32
          - 100
          - 111
          - 108
          - 111
          - 114
          - 101
          - 32
          - 101
          - 116
          - 32
          - 109
          - 111
          - 108
          - 101
          - 115
          - 116
          - 105
          - 97
          - 101
          - 32
          - 113
          - 117
          - 105
          - 97
          - 46
      required:
      - track
tags:
- name: player
  description: Player operations
