FROM golang:1.17 as builder
 
COPY ./ /github.com/JordanRad/playj/
WORKDIR /github.com/JordanRad/playj/

RUN CGO_ENABLED=0 go build -mod vendor -o '/bin/playerd' './cmd/playerd'

FROM gcr.io/distroless/base:latest
COPY --from=builder /bin/playerd /bin/playerd
CMD ["/bin/playerd"]
