openapi: 3.0.3
info:
  title: Accounts Backend Service
  description: Microservice for account management & operations
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for accounts
paths:
  /api/v1/user/register:
    post:
      tags:
      - user
      summary: register user
      operationId: user#register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestBody'
            example:
              confirmedPassword: Quia officia.
              email: Praesentium assumenda voluptas sint.
              password: Amet modi et.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Praesentium maxime omnis itaque.
components:
  schemas:
    RegisterRequestBody:
      type: object
      properties:
        confirmedPassword:
          type: string
          description: Confirmed password of the user
          example: Corporis voluptas et.
        email:
          type: string
          description: Email of the user
          example: Cum sed reprehenderit et alias asperiores.
        password:
          type: string
          description: Password of the user
          example: Magnam voluptatem sunt maiores quo est est.
      example:
        confirmedPassword: Sit aperiam.
        email: Aut ut qui exercitationem in tempora quibusdam.
        password: Ex dolorum.
      required:
      - email
      - password
      - confirmedPassword
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          description: Operation completion status
          example: Dolorum reprehenderit repellendus praesentium sed neque incidunt.
      example:
        message: Rerum distinctio minus facilis consectetur facere.
      required:
      - message
tags:
- name: user
  description: User operations
