swagger: "2.0"
info:
  title: Accounts Backend Service
  description: Microservice for account management & operations
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/account-service/accounts/login:
    post:
      tags:
      - account
      summary: login account
      operationId: account#login
      parameters:
      - name: LoginRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountLoginRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountLoginResponseBody'
            required:
            - email
            - token
            - refresh_token
            - role
      schemes:
      - http
  /api/v1/account-service/accounts/register:
    post:
      tags:
      - account
      summary: register account
      operationId: account#register
      parameters:
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountRegisterRequestBody'
          required:
          - email
          - password
          - confirmedPassword
          - firstName
          - lastName
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountRegisterResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account-service/playlists:
    get:
      tags:
      - playlist
      summary: getAccountPlaylistCollection playlist
      operationId: playlist#getAccountPlaylistCollection
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      - name: GetAccountPlaylistCollectionRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PlaylistGetAccountPlaylistCollectionRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistGetAccountPlaylistCollectionResponseBody'
            required:
            - total
            - resources
      schemes:
      - http
    post:
      tags:
      - playlist
      summary: createAccountPlaylist playlist
      operationId: playlist#createAccountPlaylist
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      - name: CreateAccountPlaylistRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PlaylistCreateAccountPlaylistRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistCreateAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
    delete:
      tags:
      - playlist
      summary: deleteAccountPlaylist playlist
      operationId: playlist#deleteAccountPlaylist
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      - name: DeleteAccountPlaylistRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PlaylistDeleteAccountPlaylistRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistDeleteAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account-service/playlists/{playlistID}:
    get:
      tags:
      - playlist
      summary: getAccountPlaylist playlist
      operationId: playlist#getAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistGetAccountPlaylistResponseBody'
            required:
            - id
            - name
            - trackIDs
      schemes:
      - http
  /api/v1/account-service/playlists/{playlistID}/tracks/{trackID}:
    post:
      tags:
      - playlist
      summary: addTrackToAccountPlaylist playlist
      operationId: playlist#addTrackToAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        type: integer
      - name: trackID
        in: path
        description: Track ID to be added
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistAddTrackToAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
    delete:
      tags:
      - playlist
      summary: removeTrackFromAccountPlaylist playlist
      operationId: playlist#removeTrackFromAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        type: integer
      - name: trackID
        in: path
        description: Track ID to be deleted
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistRemoveTrackFromAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
definitions:
  AccountLoginRequestBody:
    title: AccountLoginRequestBody
    type: object
    properties:
      email:
        type: string
        description: Email of the user
        example: Qui ullam voluptas libero id est.
      password:
        type: string
        description: Password of the user
        example: Omnis est debitis ut aliquid iste.
    example:
      email: Deserunt similique aliquam consequatur ex ratione.
      password: Ipsum suscipit.
  AccountLoginResponseBody:
    title: AccountLoginResponseBody
    type: object
    properties:
      accountID:
        type: string
        description: User's role
        example: Quia tempora a minima.
      email:
        type: string
        description: User's email
        example: Et vitae dolore temporibus dolore.
      refresh_token:
        type: string
        description: Refresh token
        example: Maxime recusandae.
      role:
        type: string
        description: User's role
        example: Aspernatur omnis.
      token:
        type: string
        description: JWT Token
        example: Delectus rerum veniam ipsam iste et.
    example:
      accountID: Voluptas modi quo.
      email: Atque est error voluptas dolorem.
      refresh_token: Asperiores et eius ducimus.
      role: Eaque voluptas.
      token: Et culpa doloremque sint ex unde sequi.
    required:
    - email
    - token
    - refresh_token
    - role
  AccountPlaylistResponseResponseBody:
    title: AccountPlaylistResponseResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Playlist id
        example: 1388887310
        format: int32
      name:
        type: string
        description: Playlist name
        example: Voluptate saepe ut.
      trackIDs:
        type: array
        items:
          type: integer
          example: 1510024335
          format: int32
        description: Array of TrackIDs
        example:
        - 869833172
        - 330648018
        - 162285353
        - 1185611931
    example:
      id: 1207683342
      name: Earum reprehenderit voluptatem rem sit voluptatum.
      trackIDs:
      - 16403832
      - 2052416964
      - 1274696105
      - 765566563
    required:
    - id
    - name
    - trackIDs
  AccountRegisterRequestBody:
    title: AccountRegisterRequestBody
    type: object
    properties:
      confirmedPassword:
        type: string
        description: Confirmed password of the user
        example: Nemo itaque.
      email:
        type: string
        description: Email of the user
        example: Omnis deserunt consectetur ipsa.
      firstName:
        type: string
        description: First name of the user
        example: Non praesentium quo molestiae.
      lastName:
        type: string
        description: Last name of the user
        example: Voluptatem voluptate.
      password:
        type: string
        description: Password of the user
        example: Quibusdam enim ratione ut ea.
    example:
      confirmedPassword: Voluptatem nisi assumenda consequatur nam.
      email: Accusamus occaecati velit.
      firstName: Nisi aut sapiente ut a libero.
      lastName: Aliquid voluptas ut tempore a praesentium.
      password: Asperiores est voluptatibus voluptas ut rem.
    required:
    - email
    - password
    - confirmedPassword
    - firstName
    - lastName
  AccountRegisterResponseBody:
    title: AccountRegisterResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Quasi repudiandae.
    example:
      message: Modi eos voluptas soluta velit debitis doloremque.
    required:
    - message
  PlaylistAddTrackToAccountPlaylistResponseBody:
    title: PlaylistAddTrackToAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Autem aut omnis.
    example:
      message: Nostrum ea neque consequatur autem optio sapiente.
    required:
    - message
  PlaylistCreateAccountPlaylistRequestBody:
    title: PlaylistCreateAccountPlaylistRequestBody
    type: object
    properties:
      name:
        type: string
        description: Playlist name
        example: Sed magnam.
    example:
      name: Fugiat quod tenetur facere reiciendis.
  PlaylistCreateAccountPlaylistResponseBody:
    title: PlaylistCreateAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Et asperiores et.
    example:
      message: Soluta sequi dolor architecto dolor ipsum repellat.
    required:
    - message
  PlaylistDeleteAccountPlaylistRequestBody:
    title: PlaylistDeleteAccountPlaylistRequestBody
    type: object
    properties:
      playlistID:
        type: integer
        example: 3889538231317184812
        format: int64
    example:
      playlistID: 7619327345437903218
  PlaylistDeleteAccountPlaylistResponseBody:
    title: PlaylistDeleteAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Ut ratione suscipit culpa non architecto.
    example:
      message: Neque dolorum quasi repellendus et quo.
    required:
    - message
  PlaylistGetAccountPlaylistCollectionRequestBody:
    title: PlaylistGetAccountPlaylistCollectionRequestBody
    type: object
    properties:
      accountID:
        type: integer
        example: 9018972027581319793
        format: int64
    example:
      accountID: 9915427560059121358
  PlaylistGetAccountPlaylistCollectionResponseBody:
    title: PlaylistGetAccountPlaylistCollectionResponseBody
    type: object
    properties:
      resources:
        type: array
        items:
          $ref: '#/definitions/AccountPlaylistResponseResponseBody'
        description: Operation completion status
        example:
        - id: 1905447668
          name: Et quasi sint.
          trackIDs:
          - 175494993
          - 1530977948
          - 844822519
          - 1773553620
        - id: 1905447668
          name: Et quasi sint.
          trackIDs:
          - 175494993
          - 1530977948
          - 844822519
          - 1773553620
        - id: 1905447668
          name: Et quasi sint.
          trackIDs:
          - 175494993
          - 1530977948
          - 844822519
          - 1773553620
      total:
        type: integer
        description: Number of resources
        example: 832930271
        format: int32
    example:
      resources:
      - id: 1905447668
        name: Et quasi sint.
        trackIDs:
        - 175494993
        - 1530977948
        - 844822519
        - 1773553620
      - id: 1905447668
        name: Et quasi sint.
        trackIDs:
        - 175494993
        - 1530977948
        - 844822519
        - 1773553620
      - id: 1905447668
        name: Et quasi sint.
        trackIDs:
        - 175494993
        - 1530977948
        - 844822519
        - 1773553620
      - id: 1905447668
        name: Et quasi sint.
        trackIDs:
        - 175494993
        - 1530977948
        - 844822519
        - 1773553620
      total: 741969238
    required:
    - total
    - resources
  PlaylistGetAccountPlaylistResponseBody:
    title: PlaylistGetAccountPlaylistResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Playlist id
        example: 1320919651
        format: int32
      name:
        type: string
        description: Playlist name
        example: Corporis magnam et nam temporibus ut sequi.
      trackIDs:
        type: array
        items:
          type: integer
          example: 1801828870
          format: int32
        description: Array of TrackIDs
        example:
        - 1920908379
        - 1917708266
        - 61170596
        - 1378979087
    example:
      id: 1480266697
      name: Rerum ut sint hic consequatur non dolorem.
      trackIDs:
      - 1389137208
      - 197063290
      - 1138334354
    required:
    - id
    - name
    - trackIDs
  PlaylistRemoveTrackFromAccountPlaylistResponseBody:
    title: PlaylistRemoveTrackFromAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Ut optio.
    example:
      message: Rem quisquam magnam sit voluptatem sit amet.
    required:
    - message
