swagger: "2.0"
info:
  title: Accounts Backend Service
  description: Microservice for account management & operations
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/account/{accountID}/playlists:
    get:
      tags:
      - account
      summary: getAccountPlaylistCollection account
      operationId: account#getAccountPlaylistCollection
      parameters:
      - name: accountID
        in: path
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountGetAccountPlaylistCollectionResponseBody'
            required:
            - total
            - resources
      schemes:
      - http
    post:
      tags:
      - account
      summary: createAccountPlaylist account
      operationId: account#createAccountPlaylist
      parameters:
      - name: accountID
        in: path
        description: Account ID
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      - name: CreateAccountPlaylistRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountCreateAccountPlaylistRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountCreateAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account/{accountID}/playlists/{playlistID}:
    get:
      tags:
      - account
      summary: getAccountPlaylist account
      operationId: account#getAccountPlaylist
      parameters:
      - name: accountID
        in: path
        description: Account ID
        required: true
        type: integer
      - name: playlistID
        in: path
        description: Playlist ID
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountGetAccountPlaylistResponseBody'
            required:
            - id
            - name
            - trackIDs
      schemes:
      - http
    delete:
      tags:
      - account
      summary: deleteAccountPlaylist account
      operationId: account#deleteAccountPlaylist
      parameters:
      - name: accountID
        in: path
        required: true
        type: integer
      - name: playlistID
        in: path
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountDeleteAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account/login:
    post:
      tags:
      - account
      summary: login account
      operationId: account#login
      parameters:
      - name: LoginRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountLoginRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountLoginResponseBody'
            required:
            - email
            - token
            - refresh_token
            - role
      schemes:
      - http
  /api/v1/account/register:
    post:
      tags:
      - account
      summary: register account
      operationId: account#register
      parameters:
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountRegisterRequestBody'
          required:
          - email
          - password
          - confirmedPassword
          - firstName
          - lastName
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountRegisterResponseBody'
            required:
            - message
      schemes:
      - http
definitions:
  AccountCreateAccountPlaylistRequestBody:
    title: AccountCreateAccountPlaylistRequestBody
    type: object
    properties:
      name:
        type: string
        description: Playlist name
        example: Nulla velit totam excepturi.
    example:
      name: Eos non rem reprehenderit mollitia et asperiores.
  AccountCreateAccountPlaylistResponseBody:
    title: AccountCreateAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Omnis voluptatem repudiandae est voluptate cumque et.
    example:
      message: Earum reprehenderit voluptatem rem sit voluptatum.
    required:
    - message
  AccountDeleteAccountPlaylistResponseBody:
    title: AccountDeleteAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Vitae soluta sequi.
    example:
      message: Architecto dolor ipsum repellat.
    required:
    - message
  AccountGetAccountPlaylistCollectionResponseBody:
    title: AccountGetAccountPlaylistCollectionResponseBody
    type: object
    properties:
      resources:
        type: array
        items:
          $ref: '#/definitions/AccountPlaylistResponseResponseBody'
        description: Operation completion status
        example:
        - id: 504519142
          name: Quo et quasi sint.
          trackIDs:
          - 175494993
          - 1530977948
          - 844822519
          - 1773553620
        - id: 504519142
          name: Quo et quasi sint.
          trackIDs:
          - 175494993
          - 1530977948
          - 844822519
          - 1773553620
        - id: 504519142
          name: Quo et quasi sint.
          trackIDs:
          - 175494993
          - 1530977948
          - 844822519
          - 1773553620
        - id: 504519142
          name: Quo et quasi sint.
          trackIDs:
          - 175494993
          - 1530977948
          - 844822519
          - 1773553620
      total:
        type: integer
        description: Number of resources
        example: 1948534894
        format: int32
    example:
      resources:
      - id: 504519142
        name: Quo et quasi sint.
        trackIDs:
        - 175494993
        - 1530977948
        - 844822519
        - 1773553620
      - id: 504519142
        name: Quo et quasi sint.
        trackIDs:
        - 175494993
        - 1530977948
        - 844822519
        - 1773553620
      - id: 504519142
        name: Quo et quasi sint.
        trackIDs:
        - 175494993
        - 1530977948
        - 844822519
        - 1773553620
      - id: 504519142
        name: Quo et quasi sint.
        trackIDs:
        - 175494993
        - 1530977948
        - 844822519
        - 1773553620
      total: 1223298755
    required:
    - total
    - resources
  AccountGetAccountPlaylistResponseBody:
    title: AccountGetAccountPlaylistResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Playlist id
        example: 1770947268
        format: int32
      name:
        type: string
        description: Playlist name
        example: Magnam aliquam fugiat quod tenetur facere reiciendis.
      trackIDs:
        type: array
        items:
          type: integer
          example: 731017624
          format: int32
        description: Array of TrackIDs
        example:
        - 504620448
        - 737124494
    example:
      id: 430175034
      name: Architecto veniam neque dolorum quasi repellendus et.
      trackIDs:
      - 905603689
      - 1774012890
    required:
    - id
    - name
    - trackIDs
  AccountLoginRequestBody:
    title: AccountLoginRequestBody
    type: object
    properties:
      email:
        type: string
        description: Email of the user
        example: Et culpa doloremque sint ex unde sequi.
      password:
        type: string
        description: Password of the user
        example: Asperiores et eius ducimus.
    example:
      email: Eaque voluptas.
      password: Voluptas modi quo.
  AccountLoginResponseBody:
    title: AccountLoginResponseBody
    type: object
    properties:
      accountID:
        type: string
        description: User's role
        example: Et vitae dolore temporibus dolore.
      email:
        type: string
        description: User's email
        example: Aliquid voluptas ut tempore a praesentium.
      refresh_token:
        type: string
        description: Refresh token
        example: Asperiores est voluptatibus voluptas ut rem.
      role:
        type: string
        description: User's role
        example: Voluptatem nisi assumenda consequatur nam.
      token:
        type: string
        description: JWT Token
        example: Accusamus occaecati velit.
    example:
      accountID: Atque est error voluptas dolorem.
      email: Delectus rerum veniam ipsam iste et.
      refresh_token: Aspernatur omnis.
      role: Quia tempora a minima.
      token: Maxime recusandae.
    required:
    - email
    - token
    - refresh_token
    - role
  AccountPlaylistResponseResponseBody:
    title: AccountPlaylistResponseResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Playlist id
        example: 934490458
        format: int32
      name:
        type: string
        description: Playlist name
        example: Voluptas libero id est.
      trackIDs:
        type: array
        items:
          type: integer
          example: 326008516
          format: int32
        description: Array of TrackIDs
        example:
        - 622950384
        - 839541566
        - 435026472
        - 1694536221
    example:
      id: 1853238414
      name: Deserunt similique aliquam consequatur ex ratione.
      trackIDs:
      - 370696800
      - 1687120001
      - 832930271
      - 1388887310
    required:
    - id
    - name
    - trackIDs
  AccountRegisterRequestBody:
    title: AccountRegisterRequestBody
    type: object
    properties:
      confirmedPassword:
        type: string
        description: Confirmed password of the user
        example: Non praesentium quo molestiae.
      email:
        type: string
        description: Email of the user
        example: Quasi repudiandae.
      firstName:
        type: string
        description: First name of the user
        example: Sequi quae accusantium praesentium sequi.
      lastName:
        type: string
        description: Last name of the user
        example: Ullam eius.
      password:
        type: string
        description: Password of the user
        example: Modi eos voluptas soluta velit debitis doloremque.
    example:
      confirmedPassword: Nisi aut sapiente ut a libero.
      email: Quibusdam enim ratione ut ea.
      firstName: Voluptatem voluptate.
      lastName: Omnis deserunt consectetur ipsa.
      password: Nemo itaque.
    required:
    - email
    - password
    - confirmedPassword
    - firstName
    - lastName
  AccountRegisterResponseBody:
    title: AccountRegisterResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Quo officia quasi modi qui.
    example:
      message: Sed libero aut.
    required:
    - message
