swagger: "2.0"
info:
  title: Accounts Backend Service
  description: Microservice for account management & operations
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/account/{accountID}/playlists:
    get:
      tags:
      - account
      summary: getUserPlaylists account
      operationId: account#getUserPlaylists
      parameters:
      - name: accountID
        in: path
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountGetUserPlaylistsResponseBody'
            required:
            - total
            - resources
      schemes:
      - http
  /api/v1/account/login:
    post:
      tags:
      - account
      summary: login account
      operationId: account#login
      parameters:
      - name: LoginRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountLoginRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountLoginResponseBody'
            required:
            - email
            - token
            - refresh_token
            - role
      schemes:
      - http
  /api/v1/account/register:
    post:
      tags:
      - account
      summary: register account
      operationId: account#register
      parameters:
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountRegisterRequestBody'
          required:
          - email
          - password
          - confirmedPassword
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountRegisterResponseBody'
            required:
            - message
      schemes:
      - http
definitions:
  AccountGetUserPlaylistsResponseBody:
    title: AccountGetUserPlaylistsResponseBody
    type: object
    properties:
      resources:
        type: array
        items:
          $ref: '#/definitions/UserSinglePlaylistResponseResponseBody'
        description: Operation completion status
        example:
        - id: 149591344
          name: Id recusandae temporibus et dolore ut.
          tracks:
          - Excepturi vero ad est.
          - Ab facilis odio facere et.
        - id: 149591344
          name: Id recusandae temporibus et dolore ut.
          tracks:
          - Excepturi vero ad est.
          - Ab facilis odio facere et.
        - id: 149591344
          name: Id recusandae temporibus et dolore ut.
          tracks:
          - Excepturi vero ad est.
          - Ab facilis odio facere et.
        - id: 149591344
          name: Id recusandae temporibus et dolore ut.
          tracks:
          - Excepturi vero ad est.
          - Ab facilis odio facere et.
      total:
        type: integer
        description: Number of resources
        example: 1970666728
        format: int32
    example:
      resources:
      - id: 149591344
        name: Id recusandae temporibus et dolore ut.
        tracks:
        - Excepturi vero ad est.
        - Ab facilis odio facere et.
      - id: 149591344
        name: Id recusandae temporibus et dolore ut.
        tracks:
        - Excepturi vero ad est.
        - Ab facilis odio facere et.
      - id: 149591344
        name: Id recusandae temporibus et dolore ut.
        tracks:
        - Excepturi vero ad est.
        - Ab facilis odio facere et.
      - id: 149591344
        name: Id recusandae temporibus et dolore ut.
        tracks:
        - Excepturi vero ad est.
        - Ab facilis odio facere et.
      total: 1087434479
    required:
    - total
    - resources
  AccountLoginRequestBody:
    title: AccountLoginRequestBody
    type: object
    properties:
      email:
        type: string
        description: Email of the user
        example: Libero aut accusamus sequi quae accusantium praesentium.
      password:
        type: string
        description: Password of the user
        example: Corporis ullam eius et quasi repudiandae voluptatem.
    example:
      email: Eos voluptas soluta.
      password: Debitis doloremque fuga.
  AccountLoginResponseBody:
    title: AccountLoginResponseBody
    type: object
    properties:
      accountID:
        type: string
        description: User's role
        example: Odit sed nostrum aut voluptatem sequi.
      email:
        type: string
        description: User's email
        example: Expedita quidem cupiditate ipsam quis.
      refresh_token:
        type: string
        description: Refresh token
        example: Et repudiandae cum corporis autem repellendus laudantium.
      role:
        type: string
        description: User's role
        example: Veniam est fuga vel et est quasi.
      token:
        type: string
        description: JWT Token
        example: Commodi id delectus dolor ex voluptatem eum.
    example:
      accountID: Quasi modi qui qui.
      email: Iure dolorem.
      refresh_token: Praesentium commodi ratione.
      role: Et eius minima quo.
      token: Itaque ut.
    required:
    - email
    - token
    - refresh_token
    - role
  AccountRegisterRequestBody:
    title: AccountRegisterRequestBody
    type: object
    properties:
      confirmedPassword:
        type: string
        description: Confirmed password of the user
        example: Minus sint rerum exercitationem.
      email:
        type: string
        description: Email of the user
        example: Recusandae nobis ut reiciendis.
      password:
        type: string
        description: Password of the user
        example: Asperiores sit molestias exercitationem molestias nobis.
    example:
      confirmedPassword: Natus et enim consectetur sit.
      email: Quo et quasi sint.
      password: Ipsum illum cupiditate corporis aut.
    required:
    - email
    - password
    - confirmedPassword
  AccountRegisterResponseBody:
    title: AccountRegisterResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Mollitia qui non culpa laborum eos corrupti.
    example:
      message: Officia nostrum quia voluptatum ut.
    required:
    - message
  UserSinglePlaylistResponseResponseBody:
    title: UserSinglePlaylistResponseResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Playlist id
        example: 1455991758
        format: int32
      name:
        type: string
        description: Playlist name
        example: Molestiae id voluptatem.
      tracks:
        type: array
        items:
          type: string
          example: Dolor omnis deserunt consectetur.
        description: Operation completion status
        example:
        - Quibusdam enim ratione ut ea.
        - Nemo itaque.
        - Nisi aut sapiente ut a libero.
        - Aliquid voluptas ut tempore a praesentium.
    example:
      id: 1405140337
      name: Occaecati velit.
      tracks:
      - Est voluptatibus voluptas.
      - Rem autem voluptatem nisi assumenda consequatur nam.
      - Et vitae dolore temporibus dolore.
      - Delectus rerum veniam ipsam iste et.
    required:
    - id
    - name
    - tracks
