swagger: "2.0"
info:
  title: Accounts Backend Service
  description: Microservice for account management & operations
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/account/{accountID}/playlists:
    get:
      tags:
      - account
      summary: getUserPlaylists account
      operationId: account#getUserPlaylists
      parameters:
      - name: accountID
        in: path
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountGetUserPlaylistsResponseBody'
            required:
            - total
            - resources
      schemes:
      - http
    post:
      tags:
      - account
      summary: createUserPlaylist account
      operationId: account#createUserPlaylist
      parameters:
      - name: accountID
        in: path
        description: Account ID
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      - name: CreateUserPlaylistRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountCreateUserPlaylistRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountCreateUserPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account/{accountID}/playlists/{playlistID}:
    delete:
      tags:
      - account
      summary: deleteUserPlaylist account
      operationId: account#deleteUserPlaylist
      parameters:
      - name: accountID
        in: path
        required: true
        type: integer
      - name: playlistID
        in: path
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountDeleteUserPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account/login:
    post:
      tags:
      - account
      summary: login account
      operationId: account#login
      parameters:
      - name: LoginRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountLoginRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountLoginResponseBody'
            required:
            - email
            - token
            - refresh_token
            - role
      schemes:
      - http
  /api/v1/account/register:
    post:
      tags:
      - account
      summary: register account
      operationId: account#register
      parameters:
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountRegisterRequestBody'
          required:
          - email
          - password
          - confirmedPassword
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountRegisterResponseBody'
            required:
            - message
      schemes:
      - http
definitions:
  AccountCreateUserPlaylistRequestBody:
    title: AccountCreateUserPlaylistRequestBody
    type: object
    properties:
      name:
        type: string
        description: Playlist name
        example: Omnis est debitis ut aliquid iste.
    example:
      name: Deserunt similique aliquam consequatur ex ratione.
  AccountCreateUserPlaylistResponseBody:
    title: AccountCreateUserPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Voluptas modi quo.
    example:
      message: Qui ullam voluptas libero id est.
    required:
    - message
  AccountDeleteUserPlaylistResponseBody:
    title: AccountDeleteUserPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Ipsum suscipit.
    example:
      message: Nobis asperiores voluptate saepe ut omnis voluptatem.
    required:
    - message
  AccountGetUserPlaylistsResponseBody:
    title: AccountGetUserPlaylistsResponseBody
    type: object
    properties:
      resources:
        type: array
        items:
          $ref: '#/definitions/UserSinglePlaylistResponseResponseBody'
        description: Operation completion status
        example:
        - id: 181822346
          name: Nobis ut reiciendis.
          tracks:
          - Sit molestias exercitationem.
          - Nobis in minus sint rerum.
        - id: 181822346
          name: Nobis ut reiciendis.
          tracks:
          - Sit molestias exercitationem.
          - Nobis in minus sint rerum.
        - id: 181822346
          name: Nobis ut reiciendis.
          tracks:
          - Sit molestias exercitationem.
          - Nobis in minus sint rerum.
        - id: 181822346
          name: Nobis ut reiciendis.
          tracks:
          - Sit molestias exercitationem.
          - Nobis in minus sint rerum.
      total:
        type: integer
        description: Number of resources
        example: 1605565041
        format: int32
    example:
      resources:
      - id: 181822346
        name: Nobis ut reiciendis.
        tracks:
        - Sit molestias exercitationem.
        - Nobis in minus sint rerum.
      - id: 181822346
        name: Nobis ut reiciendis.
        tracks:
        - Sit molestias exercitationem.
        - Nobis in minus sint rerum.
      - id: 181822346
        name: Nobis ut reiciendis.
        tracks:
        - Sit molestias exercitationem.
        - Nobis in minus sint rerum.
      - id: 181822346
        name: Nobis ut reiciendis.
        tracks:
        - Sit molestias exercitationem.
        - Nobis in minus sint rerum.
      total: 1995910554
    required:
    - total
    - resources
  AccountLoginRequestBody:
    title: AccountLoginRequestBody
    type: object
    properties:
      email:
        type: string
        description: Email of the user
        example: Nisi aut sapiente ut a libero.
      password:
        type: string
        description: Password of the user
        example: Aliquid voluptas ut tempore a praesentium.
    example:
      email: Accusamus occaecati velit.
      password: Asperiores est voluptatibus voluptas ut rem.
  AccountLoginResponseBody:
    title: AccountLoginResponseBody
    type: object
    properties:
      accountID:
        type: string
        description: User's role
        example: Modi eos voluptas soluta velit debitis doloremque.
      email:
        type: string
        description: User's email
        example: Sed libero aut.
      refresh_token:
        type: string
        description: Refresh token
        example: Ullam eius.
      role:
        type: string
        description: User's role
        example: Quasi repudiandae.
      token:
        type: string
        description: JWT Token
        example: Sequi quae accusantium praesentium sequi.
    example:
      accountID: Nemo itaque.
      email: Non praesentium quo molestiae.
      refresh_token: Omnis deserunt consectetur ipsa.
      role: Quibusdam enim ratione ut ea.
      token: Voluptatem voluptate.
    required:
    - email
    - token
    - refresh_token
    - role
  AccountRegisterRequestBody:
    title: AccountRegisterRequestBody
    type: object
    properties:
      confirmedPassword:
        type: string
        description: Confirmed password of the user
        example: Aut voluptatem.
      email:
        type: string
        description: Email of the user
        example: Non veniam est.
      password:
        type: string
        description: Password of the user
        example: Vel et est quasi unde odit sed.
    example:
      confirmedPassword: Quo officia quasi modi qui.
      email: Adipisci iure dolorem nesciunt itaque ut quo.
      password: Commodi ratione dolor et eius.
    required:
    - email
    - password
    - confirmedPassword
  AccountRegisterResponseBody:
    title: AccountRegisterResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Ex voluptatem eum dolorem.
    example:
      message: Repudiandae cum corporis autem repellendus.
    required:
    - message
  UserSinglePlaylistResponseResponseBody:
    title: UserSinglePlaylistResponseResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Playlist id
        example: 264291667
        format: int32
      name:
        type: string
        description: Playlist name
        example: Assumenda consequatur nam nam et vitae.
      tracks:
        type: array
        items:
          type: string
          example: Temporibus dolore porro.
        description: Operation completion status
        example:
        - Veniam ipsam.
        - Et aut maxime recusandae iste.
        - Omnis suscipit.
    example:
      id: 2073718892
      name: A minima ut atque est error voluptas.
      tracks:
      - Et culpa doloremque sint ex unde sequi.
      - Asperiores et eius ducimus.
    required:
    - id
    - name
    - tracks
