version: '3'

services:
  accounts-db:
    image: "postgres"
    restart: "always"
    container_name: "playj_accounts_db"
    ports:
      - "5433:5432"

    environment:
      POSTGRES_PASSWORD: "playj1307"
      POSTGRES_USER: "playj"
      POSTGRES_DB: "playj-accounts-db"

  player-db:
    image: "postgres"
    restart: "always"
    container_name: "playj_player_db"
    ports:
      - "5434:5432"

    environment:
      POSTGRES_PASSWORD: "playj1307"
      POSTGRES_USER: "playj"
      POSTGRES_DB: "playj-player-db"
