services:           
  nginx:             
    image: nginx   
    volumes:        
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/var/www/index.html
    ports:          
      - "80:80"
    depends_on:
      - paymentsd
      - playerd
      - accountsd

  paymentsd:
    image: "j2r1307/playj:payment-service"
    ports:
      - "8092:8092"
    depends_on:
      - db-paymentsd
    environment:
     - PAYMENTSD_HTTP_HOST=0.0.0.0
     - PAYMENTSD_HTTP_PORT=8092
     - PAYMENTSD_POSTGRES_HOST=db-paymentsd
     - PAYMENTSD_POSTGRES_PORT=5432
     - PAYMENTSD_POSTGRES_USER=playj
     - PAYMENTSD_POSTGRES_PASSWORD=playj1307
     - PAYMENTSD_POSTGRES_DB_NAME=playj-payments-db

  db-paymentsd:
    image: "postgres"
    restart: "always"
    ports:
      - "5435:5432"

    environment:
      POSTGRES_PASSWORD: "playj1307"
      POSTGRES_USER: "playj"
      POSTGRES_DB: "playj-payments-db"

  accountsd:
    image: "j2r1307/playj:account-service"
    ports:
      - "8091:8091"
    depends_on:
      - db-accountsd
      - paymentsd
    environment:
     - ACCOUNTSD_HTTP_HOST=0.0.0.0
     - ACCOUNTSD_HTTP_PORT=8091
     - ACCOUNTSD_POSTGRES_HOST=db-accountsd
     - ACCOUNTSD_POSTGRES_PORT=5432
     - ACCOUNTSD_POSTGRES_USER=playj
     - ACCOUNTSD_POSTGRES_PASSWORD=playj1307
     - ACCOUNTSD_POSTGRES_DB_NAME=playj-accounts-db

  db-accountsd:
    image: "postgres"
    restart: "always"
    ports:
      - "5433:5432"

    environment:
      POSTGRES_PASSWORD: "playj1307"
      POSTGRES_USER: "playj"
      POSTGRES_DB: "playj-accounts-db"

  playerd:
    image: "j2r1307/playj:player-service"
    ports:
      - "8093:8093"
    depends_on:
      - db-playerd
    environment:
     - PLAYERD_HTTP_HOST=0.0.0.0
     - PLAYERD_HTTP_PORT=8093
     - PLAYERD_POSTGRES_HOST=db-playerd
     - PLAYERD_POSTGRES_PORT=5432
     - PLAYERD_POSTGRES_USER=playj
     - PLAYERD_POSTGRES_PASSWORD=playj1307
     - PLAYERD_POSTGRES_DB_NAME=playj-player-db

  db-playerd:
    image: "postgres"
    restart: "always"
    ports:
      - "5434:5432"

    environment:
      POSTGRES_PASSWORD: "playj1307"
      POSTGRES_USER: "playj"
      POSTGRES_DB: "playj-player-db"
