services:           
  nginx:             
    image: nginx   
    volumes:        
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:          
      - "80:80"

  accountsd:
    build:
     context: ../../backend
     dockerfile: Dockerfile.accountsd
    ports:
      - "8091:8091"
    depends_on:
      - db-accountsd
    environment:
     - ACCOUNTSD_HTTP_HOST=0.0.0.0
     - ACCOUNTSD_HTTP_PORT=8091
     - ACCOUNTSD_POSTGRES_HOST=db-accountsd
     - ACCOUNTSD_POSTGRES_PORT=5432
     - ACCOUNTSD_POSTGRES_USER=playj
     - ACCOUNTSD_POSTGRES_PASSWORD=playj1307
     - ACCOUNTSD_POSTGRES_DB_NAME=playj-accounts-db

  db-accountsd:
    image: "postgres"
    restart: "always"
    ports:
      - "5433:5432"

    environment:
      POSTGRES_PASSWORD: "playj1307"
      POSTGRES_USER: "playj"
      POSTGRES_DB: "playj-accounts-db"
