name: Go Account Service CI

on:
  push:
    branches: [ main ]
    paths: 
    - 'backend/cmd/accountsd/**'
  pull_request:
    branches: [ main ]
    paths: 
    - 'backend/cmd/accountsd/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: "Run common tests"
      working-directory: ./backend/internal
      run: go test ./... -v

    - name: "Run account service tests"
      working-directory: ./backend/cmd/accountsd
      run: go test ./... -v

    - name: Build
      working-directory: ./backend/cmd/accountsd
      run: go build -v 
