name: Go Account Service CI

on:
  push:
    branches: [ main ]
    paths: 
    - 'backend/cmd/accountsd/**'
    - '.github/workflows/account-service.yml'
  pull_request:
    branches: [ main ]
    paths: 
    - 'backend/cmd/accountsd/**'

jobs:
  build:
    name: Setup, Test & Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: "Run common tests"
      working-directory: ./backend/internal
      run: go test ./... -v --cover

    - name: "Run account service tests"
      working-directory: ./backend/cmd/accountsd
      run: go test ./... -v --cover

    - name: Build
      working-directory: ./backend/cmd/accountsd
      run: go build -v 
      
      
  docker:
    needs: build
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/Dockerfile.accountsd
          push: true
          tags: latest
  
