name: Play-J Client CI

on:
  push:
    branches: [ main ]
    paths: 
    - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths: 
    - 'frontend/**'
env:
  WORKING_DIRECTORY: './frontend/playj-client'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean & Install NPM dependencies
      working-directory: ./frontend/playj-client
      run: npm ci
    - name: Build the app
      working-directory: ./frontend/playj-client
      run: sudo npm run build
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
