name: Go Player Service CI

on:
  push:
    branches: [ main ]
    paths: 
    - 'backend/cmd/playerd/**'
    - '.github/workflows/player-service.yml'
  pull_request:
    branches: [ main ]
    paths: 
    - 'backend/cmd/playerd/**'

jobs:
  build:
    name: Setup, Test & Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Run common tests
      working-directory: ./backend/internal
      run: go test ./... -v --cover

    - name: Run player service tests
      working-directory: ./backend/cmd/playerd
      run: go test ./... -v --cover

    - name: Build
      working-directory: ./backend/cmd/playerd
      run: go build -v 
      
      
  docker:
    needs: build
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Docker Build Image
        working-directory: ./backend
        run: |
          docker build --tag player-service -f Dockerfile.playerd .
          
          
      - name: Retag Docker Image
        working-directory: ./backend
        run: |
          docker tag player-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/playj:player-service

          
      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/playj:player-service
          
          
        
  
