swagger: "2.0"
info:
  title: Accounts Backend Service
  description: Microservice for account management & operations
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/account-service/accounts/login:
    post:
      tags:
      - account
      summary: login account
      operationId: account#login
      parameters:
      - name: LoginRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountLoginRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountLoginResponseBody'
            required:
            - email
            - token
            - refresh_token
            - role
      schemes:
      - http
  /api/v1/account-service/accounts/register:
    post:
      tags:
      - account
      summary: register account
      operationId: account#register
      parameters:
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountRegisterRequestBody'
          required:
          - email
          - password
          - confirmedPassword
          - firstName
          - lastName
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountRegisterResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account-service/playlists:
    get:
      tags:
      - playlist
      summary: getAccountPlaylistCollection playlist
      operationId: playlist#getAccountPlaylistCollection
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistGetAccountPlaylistCollectionResponseBody'
            required:
            - total
            - resources
      schemes:
      - http
    post:
      tags:
      - playlist
      summary: createAccountPlaylist playlist
      operationId: playlist#createAccountPlaylist
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      - name: CreateAccountPlaylistRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PlaylistCreateAccountPlaylistRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistCreateAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account-service/playlists/{playlistID}:
    get:
      tags:
      - playlist
      summary: getAccountPlaylist playlist
      operationId: playlist#getAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistGetAccountPlaylistResponseBody'
            required:
            - id
            - name
            - trackIDs
      schemes:
      - http
    put:
      tags:
      - playlist
      summary: renameAccountPlaylist playlist
      operationId: playlist#renameAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist id to modify
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      - name: RenameAccountPlaylistRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PlaylistRenameAccountPlaylistRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistRenameAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
    delete:
      tags:
      - playlist
      summary: deleteAccountPlaylist playlist
      operationId: playlist#deleteAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistDeleteAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account-service/playlists/{playlistID}/tracks/{trackID}:
    post:
      tags:
      - playlist
      summary: addTrackToAccountPlaylist playlist
      operationId: playlist#addTrackToAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        type: integer
      - name: trackID
        in: path
        description: Track ID to be added
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistAddTrackToAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
    delete:
      tags:
      - playlist
      summary: removeTrackFromAccountPlaylist playlist
      operationId: playlist#removeTrackFromAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        type: integer
      - name: trackID
        in: path
        description: Track ID to be deleted
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistRemoveTrackFromAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
definitions:
  AccountLoginRequestBody:
    title: AccountLoginRequestBody
    type: object
    properties:
      email:
        type: string
        description: Email of the user
        example: Nulla velit totam excepturi.
      password:
        type: string
        description: Password of the user
        example: Eos non rem reprehenderit mollitia et asperiores.
    example:
      email: Vitae soluta sequi.
      password: Architecto dolor ipsum repellat.
  AccountLoginResponseBody:
    title: AccountLoginResponseBody
    type: object
    properties:
      accountID:
        type: string
        description: User's role
        example: Omnis est debitis ut aliquid iste.
      email:
        type: string
        description: User's email
        example: Asperiores et eius ducimus.
      refresh_token:
        type: string
        description: Refresh token
        example: Voluptas modi quo.
      role:
        type: string
        description: User's role
        example: Qui ullam voluptas libero id est.
      token:
        type: string
        description: JWT Token
        example: Eaque voluptas.
    example:
      accountID: Earum reprehenderit voluptatem rem sit voluptatum.
      email: Deserunt similique aliquam consequatur ex ratione.
      refresh_token: Nobis asperiores voluptate saepe ut omnis voluptatem.
      role: Est voluptate cumque et.
      token: Ipsum suscipit.
    required:
    - email
    - token
    - refresh_token
    - role
  AccountPlaylistResponseResponseBody:
    title: AccountPlaylistResponseResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Playlist id
        example: 1696311533
        format: int32
      name:
        type: string
        description: Playlist name
        example: Aliquam fugiat quod tenetur facere reiciendis facere.
      trackIDs:
        type: array
        items:
          type: integer
          example: 1063571465
          format: int32
        description: Array of TrackIDs
        example:
        - 737124494
        - 430175034
    example:
      id: 576478457
      name: Veniam neque.
      trackIDs:
      - 1898964902
      - 207730188
    required:
    - id
    - name
    - trackIDs
  AccountRegisterRequestBody:
    title: AccountRegisterRequestBody
    type: object
    properties:
      confirmedPassword:
        type: string
        description: Confirmed password of the user
        example: Delectus rerum veniam ipsam iste et.
      email:
        type: string
        description: Email of the user
        example: Voluptatem nisi assumenda consequatur nam.
      firstName:
        type: string
        description: First name of the user
        example: Accusamus occaecati velit.
      lastName:
        type: string
        description: Last name of the user
        example: Asperiores est voluptatibus voluptas ut rem.
      password:
        type: string
        description: Password of the user
        example: Et vitae dolore temporibus dolore.
    example:
      confirmedPassword: Et culpa doloremque sint ex unde sequi.
      email: Quia tempora a minima.
      firstName: Maxime recusandae.
      lastName: Aspernatur omnis.
      password: Atque est error voluptas dolorem.
    required:
    - email
    - password
    - confirmedPassword
    - firstName
    - lastName
  AccountRegisterResponseBody:
    title: AccountRegisterResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Nisi aut sapiente ut a libero.
    example:
      message: Aliquid voluptas ut tempore a praesentium.
    required:
    - message
  PlaylistAddTrackToAccountPlaylistResponseBody:
    title: PlaylistAddTrackToAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Voluptatem pariatur veritatis animi amet.
    example:
      message: Odio itaque aut neque officiis.
    required:
    - message
  PlaylistCreateAccountPlaylistRequestBody:
    title: PlaylistCreateAccountPlaylistRequestBody
    type: object
    properties:
      name:
        type: string
        description: Playlist name
        example: Temporibus ut sequi cupiditate est.
    example:
      name: Fuga quae fuga quia consectetur.
  PlaylistCreateAccountPlaylistResponseBody:
    title: PlaylistCreateAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Velit quam.
    example:
      message: Magnam et.
    required:
    - message
  PlaylistDeleteAccountPlaylistResponseBody:
    title: PlaylistDeleteAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Ut optio.
    example:
      message: Rem quisquam magnam sit voluptatem sit amet.
    required:
    - message
  PlaylistGetAccountPlaylistCollectionResponseBody:
    title: PlaylistGetAccountPlaylistCollectionResponseBody
    type: object
    properties:
      resources:
        type: array
        items:
          $ref: '#/definitions/AccountPlaylistResponseResponseBody'
        description: Operation completion status
        example:
        - id: 175494993
          name: Cupiditate corporis aut vero.
          trackIDs:
          - 1143493569
          - 375885238
          - 1360704122
          - 1026396222
        - id: 175494993
          name: Cupiditate corporis aut vero.
          trackIDs:
          - 1143493569
          - 375885238
          - 1360704122
          - 1026396222
      total:
        type: integer
        description: Number of resources
        example: 1770947268
        format: int32
    example:
      resources:
      - id: 175494993
        name: Cupiditate corporis aut vero.
        trackIDs:
        - 1143493569
        - 375885238
        - 1360704122
        - 1026396222
      - id: 175494993
        name: Cupiditate corporis aut vero.
        trackIDs:
        - 1143493569
        - 375885238
        - 1360704122
        - 1026396222
      - id: 175494993
        name: Cupiditate corporis aut vero.
        trackIDs:
        - 1143493569
        - 375885238
        - 1360704122
        - 1026396222
      total: 2061705486
    required:
    - total
    - resources
  PlaylistGetAccountPlaylistResponseBody:
    title: PlaylistGetAccountPlaylistResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Playlist id
        example: 1937441679
        format: int32
      name:
        type: string
        description: Playlist name
        example: Iste iusto aut non unde maiores illum.
      trackIDs:
        type: array
        items:
          type: integer
          example: 750816143
          format: int32
        description: Array of TrackIDs
        example:
        - 1670176228
        - 1418269555
        - 1256680503
        - 1386043651
    example:
      id: 405306050
      name: Aperiam ut et.
      trackIDs:
      - 1385696766
      - 1761482889
      - 1190159261
    required:
    - id
    - name
    - trackIDs
  PlaylistRemoveTrackFromAccountPlaylistResponseBody:
    title: PlaylistRemoveTrackFromAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Et odit sed corrupti atque ut beatae.
    example:
      message: Et culpa exercitationem eveniet fuga.
    required:
    - message
  PlaylistRenameAccountPlaylistRequestBody:
    title: PlaylistRenameAccountPlaylistRequestBody
    type: object
    properties:
      name:
        type: string
        description: New playlist name
        example: Autem aut omnis.
    example:
      name: Nostrum ea neque consequatur autem optio sapiente.
  PlaylistRenameAccountPlaylistResponseBody:
    title: PlaylistRenameAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Ut sint hic consequatur non.
    example:
      message: Nihil nostrum quo repudiandae.
    required:
    - message
