swagger: "2.0"
info:
  title: Accounts Backend Service
  description: Microservice for account management & operations
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/account-service/accounts/login:
    post:
      tags:
      - account
      summary: login account
      operationId: account#login
      parameters:
      - name: LoginRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountLoginRequestBody'
          required:
          - email
          - password
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountLoginResponseBody'
            required:
            - email
            - token
            - refresh_token
            - role
      schemes:
      - http
  /api/v1/account-service/accounts/profile:
    get:
      tags:
      - account
      summary: getProfile account
      operationId: account#getProfile
      parameters:
      - name: payments_limit
        in: query
        description: Resource array size
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountGetProfileResponseBody'
            required:
            - email
            - first_name
            - last_name
            - username
            - last_payments
      schemes:
      - http
  /api/v1/account-service/accounts/register:
    post:
      tags:
      - account
      summary: register account
      operationId: account#register
      parameters:
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountRegisterRequestBody'
          required:
          - email
          - password
          - confirmedPassword
          - firstName
          - lastName
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountRegisterResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account-service/playlists:
    get:
      tags:
      - playlist
      summary: getAccountPlaylistCollection playlist
      operationId: playlist#getAccountPlaylistCollection
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistGetAccountPlaylistCollectionResponseBody'
            required:
            - total
            - resources
      schemes:
      - http
    post:
      tags:
      - playlist
      summary: createAccountPlaylist playlist
      operationId: playlist#createAccountPlaylist
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      - name: CreateAccountPlaylistRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PlaylistCreateAccountPlaylistRequestBody'
          required:
          - name
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistCreateAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account-service/playlists/{playlistID}:
    get:
      tags:
      - playlist
      summary: getAccountPlaylist playlist
      operationId: playlist#getAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistGetAccountPlaylistResponseBody'
            required:
            - id
            - name
            - trackIDs
      schemes:
      - http
    put:
      tags:
      - playlist
      summary: renameAccountPlaylist playlist
      operationId: playlist#renameAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist id to modify
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      - name: RenameAccountPlaylistRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PlaylistRenameAccountPlaylistRequestBody'
          required:
          - name
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistRenameAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
    delete:
      tags:
      - playlist
      summary: deleteAccountPlaylist playlist
      operationId: playlist#deleteAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistDeleteAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account-service/playlists/{playlistID}/tracks/{trackID}:
    post:
      tags:
      - playlist
      summary: addTrackToAccountPlaylist playlist
      operationId: playlist#addTrackToAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        type: integer
      - name: trackID
        in: path
        description: Track ID to be added
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistAddTrackToAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
    delete:
      tags:
      - playlist
      summary: removeTrackFromAccountPlaylist playlist
      operationId: playlist#removeTrackFromAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        type: integer
      - name: trackID
        in: path
        description: Track ID to be deleted
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PlaylistRemoveTrackFromAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
definitions:
  AccountGetProfileResponseBody:
    title: AccountGetProfileResponseBody
    type: object
    properties:
      email:
        type: string
        description: Operation completion status
        example: Veritatis animi amet dolores odio itaque.
      first_name:
        type: string
        description: First Name
        example: Neque officiis assumenda et.
      last_name:
        type: string
        description: Last Name
        example: Sed corrupti atque ut beatae id et.
      last_payments:
        type: array
        items:
          $ref: '#/definitions/PaymentResponseResponseBody'
        description: Array of last payments
        example:
        - amount: 0.22779948
          createdAt: Qui qui sed.
          id: 16587001386555198618
          paymentNumber: Aut accusamus sequi quae accusantium praesentium.
        - amount: 0.22779948
          createdAt: Qui qui sed.
          id: 16587001386555198618
          paymentNumber: Aut accusamus sequi quae accusantium praesentium.
        - amount: 0.22779948
          createdAt: Qui qui sed.
          id: 16587001386555198618
          paymentNumber: Aut accusamus sequi quae accusantium praesentium.
      username:
        type: string
        description: Username
        example: Exercitationem eveniet.
    example:
      email: Voluptate qui corporis.
      first_name: Debitis similique.
      last_name: Dolore dolor impedit.
      last_payments:
      - amount: 0.22779948
        createdAt: Qui qui sed.
        id: 16587001386555198618
        paymentNumber: Aut accusamus sequi quae accusantium praesentium.
      - amount: 0.22779948
        createdAt: Qui qui sed.
        id: 16587001386555198618
        paymentNumber: Aut accusamus sequi quae accusantium praesentium.
      - amount: 0.22779948
        createdAt: Qui qui sed.
        id: 16587001386555198618
        paymentNumber: Aut accusamus sequi quae accusantium praesentium.
      username: Quia excepturi et alias.
    required:
    - email
    - first_name
    - last_name
    - username
    - last_payments
  AccountLoginRequestBody:
    title: AccountLoginRequestBody
    type: object
    properties:
      email:
        type: string
        description: Email of the user
        example: Maiores illum debitis.
      password:
        type: string
        description: Password of the user
        example: Illo libero et.
    example:
      email: Qui nemo aperiam.
      password: Et dolor aliquam rem quasi incidunt voluptatem.
    required:
    - email
    - password
  AccountLoginResponseBody:
    title: AccountLoginResponseBody
    type: object
    properties:
      accountID:
        type: string
        description: User's role
        example: Nihil nostrum quo repudiandae.
      email:
        type: string
        description: User's email
        example: Magnam et.
      refresh_token:
        type: string
        description: Refresh token
        example: Fuga quae fuga quia consectetur.
      role:
        type: string
        description: User's role
        example: Ut sint hic consequatur non.
      token:
        type: string
        description: JWT Token
        example: Temporibus ut sequi cupiditate est.
    example:
      accountID: Illum iste iusto aut non.
      email: Autem aut omnis.
      refresh_token: Ut optio.
      role: Rem quisquam magnam sit voluptatem sit amet.
      token: Nostrum ea neque consequatur autem optio sapiente.
    required:
    - email
    - token
    - refresh_token
    - role
  AccountPlaylistResponseResponseBody:
    title: AccountPlaylistResponseResponseBody
    type: object
    properties:
      createdAt:
        type: string
        description: Time of creation
        example: Nisi molestias consequatur quae et debitis similique.
      id:
        type: integer
        description: Playlist id
        example: 938743052
        format: int32
      name:
        type: string
        description: Playlist name
        example: Animi architecto est perferendis ratione ut.
      trackIDs:
        type: array
        items:
          type: integer
          example: 432053022
          format: int32
        description: Array of TrackIDs
        example:
        - 286363919
        - 1244680467
    example:
      createdAt: Itaque reprehenderit aperiam officia rem corporis.
      id: 231716508
      name: Et molestiae expedita explicabo ut.
      trackIDs:
      - 1810263819
      - 284614766
      - 606719987
      - 906570195
    required:
    - id
    - name
    - trackIDs
  AccountRegisterRequestBody:
    title: AccountRegisterRequestBody
    type: object
    properties:
      confirmedPassword:
        type: string
        description: Confirmed password of the user
        example: Soluta sequi dolor architecto dolor ipsum repellat.
      email:
        type: string
        description: Email of the user
        example: Excepturi assumenda eos non rem reprehenderit mollitia.
      firstName:
        type: string
        description: First name of the user
        example: Voluptatem rem sit.
      lastName:
        type: string
        description: Last name of the user
        example: Impedit nulla velit.
      password:
        type: string
        description: Password of the user
        example: Asperiores et.
    example:
      confirmedPassword: Omnis velit quam.
      email: Ut ratione suscipit culpa non architecto.
      firstName: Sed magnam.
      lastName: Fugiat quod tenetur facere reiciendis.
      password: Neque dolorum quasi repellendus et quo.
    required:
    - email
    - password
    - confirmedPassword
    - firstName
    - lastName
  AccountRegisterResponseBody:
    title: AccountRegisterResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Voluptatem repudiandae est voluptate cumque.
    example:
      message: Veniam earum.
    required:
    - message
  PaymentResponseResponseBody:
    title: PaymentResponseResponseBody
    type: object
    properties:
      amount:
        type: number
        example: 0.053421363
        format: float
      createdAt:
        type: string
        example: Ut eaque accusantium ullam et quod et.
      id:
        type: integer
        example: 5920216772656266608
        format: int64
      paymentNumber:
        type: string
        example: Quia vel.
    example:
      amount: 0.1298161
      createdAt: Ut eligendi molestiae velit minus et excepturi.
      id: 16090067729384112293
      paymentNumber: Assumenda vel reiciendis et quidem deleniti.
    required:
    - id
    - createdAt
    - paymentNumber
    - amount
  PlaylistAddTrackToAccountPlaylistResponseBody:
    title: PlaylistAddTrackToAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Earum unde porro aut iure.
    example:
      message: Enim id animi fugiat rerum rerum.
    required:
    - message
  PlaylistCreateAccountPlaylistRequestBody:
    title: PlaylistCreateAccountPlaylistRequestBody
    type: object
    properties:
      name:
        type: string
        description: Playlist name
        example: Quae voluptatibus recusandae excepturi deserunt rem.
    example:
      name: Doloribus consectetur corporis doloribus autem et ipsa.
    required:
    - name
  PlaylistCreateAccountPlaylistResponseBody:
    title: PlaylistCreateAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Aut itaque eveniet consequatur sed commodi.
    example:
      message: Delectus reiciendis.
    required:
    - message
  PlaylistDeleteAccountPlaylistResponseBody:
    title: PlaylistDeleteAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Aut ut adipisci molestiae.
    example:
      message: Amet id et voluptas.
    required:
    - message
  PlaylistGetAccountPlaylistCollectionResponseBody:
    title: PlaylistGetAccountPlaylistCollectionResponseBody
    type: object
    properties:
      resources:
        type: array
        items:
          $ref: '#/definitions/AccountPlaylistResponseResponseBody'
        description: Operation completion status
        example:
        - createdAt: Libero dolore aliquid.
          id: 604293069
          name: Ratione ut ea nostrum nemo itaque.
          trackIDs:
          - 392522440
          - 2065925810
          - 1687841759
          - 1929963202
        - createdAt: Libero dolore aliquid.
          id: 604293069
          name: Ratione ut ea nostrum nemo itaque.
          trackIDs:
          - 392522440
          - 2065925810
          - 1687841759
          - 1929963202
        - createdAt: Libero dolore aliquid.
          id: 604293069
          name: Ratione ut ea nostrum nemo itaque.
          trackIDs:
          - 392522440
          - 2065925810
          - 1687841759
          - 1929963202
      total:
        type: integer
        description: Number of resources
        example: 1331689379
        format: int32
    example:
      resources:
      - createdAt: Libero dolore aliquid.
        id: 604293069
        name: Ratione ut ea nostrum nemo itaque.
        trackIDs:
        - 392522440
        - 2065925810
        - 1687841759
        - 1929963202
      - createdAt: Libero dolore aliquid.
        id: 604293069
        name: Ratione ut ea nostrum nemo itaque.
        trackIDs:
        - 392522440
        - 2065925810
        - 1687841759
        - 1929963202
      - createdAt: Libero dolore aliquid.
        id: 604293069
        name: Ratione ut ea nostrum nemo itaque.
        trackIDs:
        - 392522440
        - 2065925810
        - 1687841759
        - 1929963202
      total: 1985495688
    required:
    - total
    - resources
  PlaylistGetAccountPlaylistResponseBody:
    title: PlaylistGetAccountPlaylistResponseBody
    type: object
    properties:
      createdAt:
        type: string
        description: Time of creation
        example: Non id.
      id:
        type: integer
        description: Playlist id
        example: 1772702680
        format: int32
      name:
        type: string
        description: Playlist name
        example: Sequi quia voluptas dolorem minima corrupti.
      trackIDs:
        type: array
        items:
          type: integer
          example: 492491542
          format: int32
        description: Array of TrackIDs
        example:
        - 996887948
        - 165015854
        - 447998379
        - 1739411566
    example:
      createdAt: Non iure tenetur.
      id: 158334141
      name: Non accusamus ut iste.
      trackIDs:
      - 893323924
      - 20533173
      - 663517178
    required:
    - id
    - name
    - trackIDs
  PlaylistRemoveTrackFromAccountPlaylistResponseBody:
    title: PlaylistRemoveTrackFromAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Assumenda magnam in voluptate tenetur deserunt.
    example:
      message: Illo eos non veritatis non laudantium.
    required:
    - message
  PlaylistRenameAccountPlaylistRequestBody:
    title: PlaylistRenameAccountPlaylistRequestBody
    type: object
    properties:
      name:
        type: string
        description: New playlist name
        example: Omnis beatae.
    example:
      name: Explicabo at et dolor sed.
    required:
    - name
  PlaylistRenameAccountPlaylistResponseBody:
    title: PlaylistRenameAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Molestiae sint asperiores incidunt eligendi.
    example:
      message: Itaque totam.
    required:
    - message
